spring:
  datasource:
    password: root
    username: 333
    url: jdbc:mysql://localhost:3306/recruiter?serverTimezone=UTC&userUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#整合Mybatis
mybatis:
  type-aliases-package: com.life.POJO
  mapper-locations: classpath:mybatis/Mapper/*.xml
