server:
  port: 9090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # springboot2.6.7匹配swagger
    multipart: # 文件上传下载配置
      max-file-size: 20MB # 用来指定服务器端文件大小的限制
      max-request-size: 10MB # 用来指定客户端文件大小的限制
      location: D:/Recruiter/temp/
  messages: # 国际化文件配置
    basename: ./i18n/*
  application:
    name: Recruiter-dev # 项目名
  datasource: # 数据库配置
    password: root
    username: 333
    url: jdbc:mysql://localhost:3306/recruiter?serverTimezone=GMT&userUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 1
      max-wait: 6000000
      minIdle: 5
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf: # thymeleaf 配置
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。

#整合Mybatis
mybatis:
  mapper-locations: classpath:mybatis/Mapper/**/*.xml
  type-aliases-package: com.life.POJO


# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

  #设置log
logging:
  file:
    name: ./log/logger.log
  level:
    root: info

